- name: Setup Flatpak
  hosts: host1
  become: true
  tasks:
    - name: Ensure the system is updated 
      apt: 
        update_cache: yes 
    - name: Install Flatpak 
      apt: 
        name: flatpak 
        state: present 
    - name: Add the Flathub repository
      command: flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
    - name: Install DBeaver
      flatpak:
        name: io.dbeaver.DBeaverCommunity
        method: system
        state: present
